ignores:
  - "@babel/*"
  - "@stryker-mutator/jest-runner"
  - "@types/jest"
  - "babel-jest"
  - mdast
  - remark-cli
  - remark-lint
  - remark-preset-*
  - rimraf
  - prettier-plugin-*
  - ts-jest
  - unist
