badges:
  - npm/v
  - id: github/workflow/status
    about:
      workflowFile: ci.yml
      workflowName: CI
  - github/license
  - codecov/c
  - badge-roll

settings:
  separator: newline
  provider: shields
  position: below-lead

about:
  branch: main
