badges:
  - npm/v
  - github/workflow/status
  - github/license
  - codecov/c
  - badge-roll

settings:
  separator: newline
  provider: shields
  position: below-lead

about:
  branch: main
  workflow: ci
