name: Mutate

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm ci

      - name: Mutate
        run: npm run test:mutate
